rates:
  build: ../02_rates
  volumes:
   - /logs
  ports:
   - "9000:8080"

elasticsearch:
  image: elasticsearch
  ports:
   - "9200:9200"

kibana:
  image: kibana
  ports:
   - "9090:5601"
  links:
   - elasticsearch

logstash:
  image: logstash
  volumes:
   - ./logstash:/config-dir
  volumes_from:
   - rates
  net: "container:elasticsearch"
  command: logstash -f /config-dir/logstash.conf

