portal_data:
  image: ubuntu
  volumes:
   - /portal/static
  command: /bin/true

portal:
  build: ../03_portal
  ports:
   - "8888:8888"
  links:
   - rates
  volumes_from:
    - portal_data

rates:
  build: ../02_rates
